#! python

import os
import sys
import subprocess

def convert_all():
    """Convert all files in the current directory from .jpeg to .eps files"""
    for file in os.listdir(os.getcwd()):
        if file.endswith(".jpeg"):
            subprocess.call(["convert", file, '-compress', 'jpeg', f"eps2:{file[:-5]}.eps"])
        if file.endswith(".jpg"):
            subprocess.call(["convert", file, '-compress', 'jpeg', f"eps2:{file[:-4]}.eps"])
        if file.endswith(".png"):
            subprocess.call(["convert", file, f"{file[:-4]}.eps"])

if __name__ == "__main__":
    print("convert")
    convert_all()

